name: Build and Publish NuGet package for Production

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

env:
  PACKAGE_PATH: './nupkg'
  PACKAGE_NAME: 'nuget-package'

jobs:
  Prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      packagePath: ${{ steps.set_vars.outputs.packagePath }}
      packageName: ${{ steps.set_vars.outputs.packageName }}

    steps:
    - name: Extract version from release
      id: get_version
      run: |
        VERSION=$(echo "${{ github.event.release.name }}" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Set package variables
      id: set_vars
      run: |
        echo "packagePath=${{ env.PACKAGE_PATH }}" >> $GITHUB_OUTPUT
        echo "packageName=${{ env.PACKAGE_NAME }}" >> $GITHUB_OUTPUT

  Build:
    needs: Prepare
    uses: ./.github/workflows/shared-build-nuget.yml
    with:
      version: ${{ needs.Prepare.outputs.version }}
      packagePath: ${{ needs.Prepare.outputs.packagePath }}
      packageName: ${{ needs.Prepare.outputs.packageName }}

  Publish:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Download NuGet package
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{ env.PACKAGE_PATH }}

      - name: Publish to NuGet
        run: dotnet nuget push ${{ env.PACKAGE_PATH }}/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
