# -----------------------------------------------------------------------------
# GitHub Actions Workflow: Invoke Auto Tag
#
# Purpose:
#   This workflow triggers the reusable auto-tag workflow defined in the
#   central repository. It passes the .csproj file path as input.
# -----------------------------------------------------------------------------

name: Invoke Auto Tag

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    uses: linke-engineering/.github/workflows/release-auto-tag.yml@v1.0.0
    secrets: inherit
    with:
      project_file: 'src/CalendrierRepublicain/CalendrierRepublicain.csproj'