# -------------------------------------------------------------------------------------------------
# GitHub Actions Reusable Workflow: Auto Tag on Merge to Main
#
# Purpose:
#   Automatically create a Git tag based on the version in the specified project file when a merge
#   occurs on the main branch.
#
# Prerequisites:
#   - The project file must contain a <Version> element with the version number in the format:
#     <Version>1.2.3</Version>.
# -------------------------------------------------------------------------------------------------

name: Auto Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    env:
      PROJECT_FILE: 'src/CalendrierRepublicain/CalendrierRepublicain.csproj'

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Extract version from project file
        run: |
          VERSION=$(grep -oPm1 '(?<=<Version>)[^<]+' ${{ env.PROJECT_FILE }} || echo "0.0.0")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Git tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          TAG_NAME="v${{ env.VERSION }}"

          if git rev-parse "$TAG_NAME" >/dev/null 2>&1 || git ls-remote --exit-code --tags origin "refs/tags/$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists. Skipping tag creation."
            exit 0
          fi

          git tag -a "$TAG_NAME" -m "Release version ${{ env.VERSION }}"
          git push origin "$TAG_NAME"